Setting up project infrastructure
OCHA-DAP/hapi-sqlalchemy-schema pull request #4
Opened 2023-10-06 14:00 UTC by SimonbJohnson

2023-10-09 07:53 UTC, turnerm requested changes
This looks great! In addition to the changes I've specified, could you:

* run pre-commit on all the files? For example, I see that a few have a missing newline, which should be fixed by one of the hooks.  
* update the changelog

By the way were you able to test the new GHA hook? IIRC you have to push to main first before the action will appear on the menu. In that case we can just cross our fingers and merge, and if there are any bugs we'll fix them :)

2023-10-09 07:53 UTC, turnerm commented on .config/coveragerc
This isn't needed since we don't have any tests

2023-10-09 07:53 UTC, turnerm commented on .config/pre-commit-config.yaml
If you run `pre-commit autoupdate` you can bring all the hooks to the latest version

2023-10-09 07:53 UTC, turnerm commented on .config/ruff.toml
> +known-local-folder = ["hdx"]
These lines can be removed

2023-10-09 07:53 UTC, turnerm commented on .github/workflows/publish.yaml
> +    - uses: actions/checkout@v3
`checkout` now has v4

2023-10-09 07:53 UTC, turnerm commented on pyproject.toml
> +# Tests
You can take out this section for now

2023-10-09 07:53 UTC, turnerm commented on pyproject.toml
> +timezones = ["hdx-python-api"]
This should be "hdx-python-database", hopefully that will trim down the requirements file a bit

2023-10-10 22:16 UTC, SimonbJohnson commented
@turnerm - I've updated for the request changes.  I've not tested the github actions yet, as you say it is not available until in main.

2023-10-11 11:12 UTC, turnerm commented on src/hapi_schema/databasequeries.py
Oops one last thing, can you remove this file, it's not needed

2023-10-11 11:14 UTC, turnerm commented
I realized that we forgot to properly implement the extras because there is no import check. However Mike's changes in HAPI 215 mean we won't have to have the extras anymore so I think that's fine.

2023-10-12 09:55 UTC, merged